name: Deploy en AWS lighsail

on:
    push:
        branches: ['main']

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Conexion SSH
            uses: webfactory/ssh-agent@v0.5.3
            with:
              ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

          - name: Despliegue en lightsail
            run: |
              ssh -o strictHostKeyCheking = no
              ubuntu@34.238.80.206 << 'EOF'
              cd /var/www/html
              sudo rm -rf *
              git clone https://github.com/ItaloOrganization/PruebaGitFlow.git .
              EOF