name: Integracion a DockerHub

on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login a DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docer Image
        run: |
          docker buid -t pagina-prueba .
      - name: push Docker File to Docker hub
        run: |
          docker tag image-pagina ${{secrets.DOCKERHUB_USERNAME}}/pagina-prueba:latest
          docker push ${{secrets.DOCKERHUB_USERNAME}}/
          pagina-prueba:latest
